//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_17_S_CC6001NI_14046931_Kiran_Shahi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class EQUIP_SESS
    {
        [DisplayName("Equipment Session ID")]
        public int EQUIP_SESS_ID { get; set; }
        public string SESSION_CODE { get; set; }
        public int EQUIPMENT_ID { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
