//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_17_S_CC6001NI_14046931_Kiran_Shahi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SESSION_STAFF
    {
        [DisplayName("Session Staff ID")]
        public int SESSION_STAFF_ID { get; set; }
        public int STAFF_ID { get; set; }
        public string SESSION_CODE { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
