//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_17_S_CC6001NI_14046931_Kiran_Shahi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSION()
        {
            this.EQUIP_SESS = new HashSet<EQUIP_SESS>();
            this.SESSION_STAFF = new HashSet<SESSION_STAFF>();
        }

        [DisplayName("Session Code")]
        public string SESSION_CODE { get; set; }
        [DisplayName("Start Time")]
        public decimal START_TIME { get; set; }
        [DisplayName("Session Period")]
        public int PERIOD { get; set; }
        [DisplayName("Activity")]
        public int ACTIVITY_ID { get; set; }
        [DisplayName("Room")]
        public int ROOM_ID { get; set; }
        public string REF_NO { get; set; }
    
        public virtual ACTIVITy ACTIVITy { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIP_SESS> EQUIP_SESS { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSION_STAFF> SESSION_STAFF { get; set; }
    }
}
