//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016_17_S_CC6001NI_14046931_Kiran_Shahi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.SESSION_STAFF = new HashSet<SESSION_STAFF>();
        }

        [DisplayName("Staff ID")]
        public int STAFF_ID { get; set; }
        [DisplayName("Staff Name")]
        public string STAFF_NAME { get; set; }
        [DisplayName("Staff Designation")]
        public string STAFF_DESIGNATION { get; set; }
        [DisplayName("Staff Type")]
        public string STAFF_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSION_STAFF> SESSION_STAFF { get; set; }
    }
}
